### ISSUE TITLE
Failed to open the product with existing date.

### ISSUE THREAD

**Issue by lelerer** [AY2122S2-CS2113-F10-3/tp#31]
<img width="968" alt="Screenshot 2022-04-01 at 17 31 31" src="https://user-images.githubusercontent.com/60871570/161237747-90623d58-eaa1-4f2f-bff2-d79f5fef0496.png">

The app cannot be opened with existing data and will return some errors.

**Comment by mafpovbul** [comment]
Storage Exception handling added
