### ISSUE TITLE
[PE-D] UG can add more formatting

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-3/tp#39]
It's suggested to  use formtting (e.g. font style, size and colour, mark-ups, callouts, bold, italics) and layout (e.g. white space, alignment) to make it more user-friendly.

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Ch40gRv1-Mu/ped#8

**Comment by timchang27** [comment]
Done. Thank you for the feedback :)
