### ISSUE TITLE
[PE-D] Product name wrong in User Guide

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-3/tp#46]
![Screenshot 2022-04-01 at 16.58.24.png](https://raw.githubusercontent.com/lelerer/ped/main/files/d4c1ae7d-a264-496c-a6dd-e6f82315bc45.png)

![Screenshot 2022-04-01 at 16.58.41.png](https://raw.githubusercontent.com/lelerer/ped/main/files/6c482e47-e21f-480d-b1d1-fb025ceb9d0b.png)

The product name should be Travel Agency Booking Reservation System according to the welcome message, while the name reflected on UG is Duke

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: lelerer/ped#2

**Comment by edemirkirkan** [comment]
Solved
