### ISSUE TITLE
[PE-D] Product allowing start date to be easier than end date

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-3/tp#50]
![Screenshot 2022-04-01 at 17.01.49.png](https://raw.githubusercontent.com/lelerer/ped/main/files/5e04d4a0-000f-42df-ad15-672b7dee07b1.png)
As shown in the screen shot, the start date specified by the user is earlier than the end date, yet the Package was still successfully added!

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: lelerer/ped#3

**Comment by mafpovbul** [comment]
Date validity done
