### ISSUE TITLE
[PE-D] No error message nor success message

### ISSUE THREAD

**Issue by nus-se-script** [AY2122S2-CS2113-F10-3/tp#55]
![Screenshot 2022-04-01 at 17.08.17.png](https://raw.githubusercontent.com/lelerer/ped/main/files/e506a398-04f2-438a-a8d6-ea30fcbe00c5.png)
When I try to view the reservations in a non-exist package, I should receive an error indicating I am doing something illegal, yet the product returns nothing

-------------
Labels: `severity.High` `type.FunctionalityBug`
original: lelerer/ped#5

**Comment by mafpovbul** [comment]
Added "No reservations added yet!" message
