### ISSUE TITLE
[PE-D] Not clear on how to exit from the software.

### ISSUE THREAD

**Issue by nus-pe-script** [AY2122S2-CS2113-F10-3/tp#60]
![Screenshot 2022-04-01 at 17.14.35.png](https://raw.githubusercontent.com/lelerer/ped/main/files/f0282f1e-7926-4c93-ba69-7626229444f3.png)
As a user, I cannot exit from your app using `exit` command, and I couldn't find the right command to use from your UserGuide either.

-------------
Labels: `type.FunctionalityBug` `severity.Medium`
original: lelerer/ped#7

**Comment by edemirkirkan** [comment]
Solved
